export async function GET() {
  const members = [
    // --- ACTIVE (6) ---
    {
      id: 'aria-lindqvist',
      initials: 'AL',
      name: 'Aria Lindqvist',
      companyName: 'Northwave Inc',
      location: 'Stockholm, Sweden',
      email: 'aria.lindqvist@northwave.io',
      mobileNumber: '+46 8 123 4567',
      plan: 'Growth',
      planPrice: '$49/monthly',
      status: 'ACTIVE',
      payment: 'PAID',
      expiryDate: 'Jun 6, 2026',
      daysLeft: '18d left',
      registrationDate: '14-Jan-2026',
    },
    {
      id: 'tomas-beltran',
      initials: 'TB',
      name: 'Tomás Beltrán',
      companyName: 'Meridian Shop',
      location: 'Madrid, Spain',
      email: 'tbeltran@meridian.shop',
      mobileNumber: '+34 91 123 4567',
      plan: 'Starter',
      planPrice: '$19/monthly',
      status: 'ACTIVE',
      payment: 'PENDING',
      expiryDate: 'May 23, 2026',
      daysLeft: '4d left',
      registrationDate: '18-Feb-2026',
    },
    {
      id: 'mateo-ferrari',
      initials: 'MF',
      name: 'Mateo Ferrari',
      companyName: 'Brightboard Co',
      location: 'Milan, Italy',
      email: 'mateo.f@brightboard.co',
      mobileNumber: '+39 02 123 4567',
      plan: 'Enterprise',
      planPrice: '$249/monthly',
      status: 'ACTIVE',
      payment: 'PAID',
      expiryDate: 'Jul 14, 2026',
      daysLeft: '56d left',
      registrationDate: '02-Apr-2026',
    },
    {
      id: 'hana-okonkwo',
      initials: 'HO',
      name: 'Hana Okonkwo',
      companyName: 'Looplane Studio',
      location: 'Lagos, Nigeria',
      email: 'hana@looplane.studio',
      mobileNumber: '+234 803 123 4567',
      plan: 'Growth',
      planPrice: '$49/monthly',
      status: 'ACTIVE',
      payment: 'PAID',
      expiryDate: 'May 31, 2026',
      daysLeft: '12d left',
      registrationDate: '19-Apr-2026',
    },
    {
      id: 'sarah-jenkins',
      initials: 'SJ',
      name: 'Sarah Jenkins',
      companyName: 'Apex Data',
      location: 'London, UK',
      email: 'sarah@apexdata.co.uk',
      mobileNumber: '+44 20 7946 0192',
      plan: 'Scale',
      planPrice: '$99/monthly',
      status: 'ACTIVE',
      payment: 'PAID',
      expiryDate: 'Jun 18, 2026',
      daysLeft: '30d left',
      registrationDate: '05-May-2026',
    },
    {
      id: 'yuki-tanaka',
      initials: 'YT',
      name: 'Yuki Tanaka',
      companyName: 'Nippon Media',
      location: 'Tokyo, Japan',
      email: 'y.tanaka@nipponmedia.jp',
      mobileNumber: '+81 3 5555 0142',
      plan: 'Starter',
      planPrice: '$19/monthly',
      status: 'ACTIVE',
      payment: 'PAID',
      expiryDate: 'Jun 22, 2026',
      daysLeft: '34d left',
      registrationDate: '12-May-2026',
    },

    // --- PENDING (3) ---
    {
      id: 'liam-oconnor',
      initials: 'LO',
      name: "Liam O'Connor",
      companyName: 'Emerald Tech',
      location: 'Dublin, Ireland',
      email: 'liam@emeraldtech.ie',
      mobileNumber: '+353 1 496 0123',
      plan: 'Growth',
      planPrice: '$49/monthly',
      status: 'PENDING',
      payment: 'PENDING',
      expiryDate: 'Jun 19, 2026',
      daysLeft: '31d left',
      registrationDate: '20-May-2026',
    },
    {
      id: 'chloe-dupont',
      initials: 'CD',
      name: 'Chloé Dupont',
      companyName: 'Atelier Design',
      location: 'Paris, France',
      email: 'chloe@atelierdesign.fr',
      mobileNumber: '+33 1 42 27 78 90',
      plan: 'Starter',
      planPrice: '$19/monthly',
      status: 'PENDING',
      payment: 'PENDING',
      expiryDate: 'Jun 20, 2026',
      daysLeft: '32d left',
      registrationDate: '20-May-2026',
    },
    {
      id: 'noah-al-fayed',
      initials: 'NF',
      name: 'Noah Al-Fayed',
      companyName: 'Crescent Trading',
      location: 'Cairo, Egypt',
      email: 'noah@crescent.com.eg',
      mobileNumber: '+20 2 2720 0110',
      plan: 'Scale',
      planPrice: '$99/monthly',
      status: 'PENDING',
      payment: 'PENDING',
      expiryDate: 'Jun 21, 2026',
      daysLeft: '33d left',
      registrationDate: '20-May-2026',
    },

    // --- SUSPENDED (2) ---
    {
      id: 'priya-raghavan',
      initials: 'PR',
      name: 'Priya Raghavan',
      companyName: 'Orbit Labs',
      location: 'Bangalore, India',
      email: 'priya@orbitlabs.dev',
      mobileNumber: '+91 98765 43210',
      plan: 'Scale',
      planPrice: '$99/monthly',
      status: 'SUSPENDED',
      payment: 'OVERDUE',
      expiryDate: 'May 13, 2026',
      daysLeft: 'Expired 6d ago',
      registrationDate: '22-Mar-2026',
    },
    {
      id: 'marcus-vance',
      initials: 'MV',
      name: 'Marcus Vance',
      companyName: 'Vance Logistics',
      location: 'Chicago, USA',
      email: 'marcus@vancelogistics.com',
      mobileNumber: '+1 312 555 0199',
      plan: 'Growth',
      planPrice: '$49/monthly',
      status: 'SUSPENDED',
      payment: 'OVERDUE',
      expiryDate: 'May 10, 2026',
      daysLeft: 'Expired 9d ago',
      registrationDate: '10-Feb-2026',
    },

    // --- INCOMPLETE (1) ---
    {
      id: 'elena-rostova',
      initials: 'ER',
      name: 'Elena Rostova',
      companyName: 'Aurora Media',
      location: 'Moscow, Russia',
      email: 'elena@auroramedia.ru',
      mobileNumber: '+7 495 123 4567',
      plan: 'Starter',
      planPrice: '$19/monthly',
      status: 'INCOMPLETE',
      payment: 'PENDING',
      expiryDate: 'Jun 25, 2026',
      daysLeft: '37d left',
      registrationDate: '20-May-2026',
    },

    // --- INACTIVE (1) ---
    {
      id: 'isabella-rossi',
      initials: 'IR',
      name: 'Isabella Rossi',
      companyName: 'Rossi Moda',
      location: 'Rome, Italy',
      email: 'isabella@rossimoda.it',
      mobileNumber: '+39 06 1234567',
      plan: 'Growth',
      planPrice: '$49/monthly',
      status: 'INACTIVE',
      payment: 'OVERDUE',
      expiryDate: 'Apr 30, 2026',
      daysLeft: 'Expired 20d ago',
      registrationDate: '05-Mar-2026',
    },
  ];

  return Response.json(members);
}
